### ISSUE TITLE
custom aspects

### ISSUE THREAD

**Issue by wimco** [agea/CmisJS#21]
Does CmisJS support reading & writing custom Alfresco aspects?

From my object succinctProperties I can see that my object has the following cmis:secondaryObjectTypeIds:
S:vz:Common
S:vz:pleadings
S:wba:consultation

Which matches my custom aspects;  But how do I read the values and write back to them?

**Comment by agea** [comment]
If you are using an Alfresco version with Cmis 1.1 bindings (like the 4.2 version)  you should see all properties of all aspects associated with your node when calling session.getObject(), and your able to write them as any other property

In prior versions you can retrieve custom aspect properties only through cmis queries

**Comment by wimco** [comment]
I am using CMIS version 1.1 Alfresco 4.2d CE) through the following URL:
/alfresco/api/-default-/public/cmis/versions/1.1/browser

However my object only contains a list of cmis:secondaryObjectTypeIds as an Array, listing the aspects added (but not their fields or values).  Is there a special way to retrieve them?

Will try against Alfresco 5.0 too.

Thanks for any help!

**Comment by agea** [comment]
The cmis browser binding in Alfresco 4.2 was marked as EXPERIMENTAL, I think the only way to retrieve aspect properties is through a CMIS query: http://wiki.alfresco.com/wiki/CMIS#Aspect_Query
