### ISSUE TITLE
Cannot read property 'rootFolderUrl' of undefined

### ISSUE THREAD

**Issue by YogeshGK** [agea/CmisJS#23]
var url = "http://xxx:8080/alfresco/cmisbrowser";
	var session = cmis.createSession(url);
	session.setCredentials('admin','7Tablets!');

	//works fine
	session.loadRepositories().ok(function (data){
	});
	
	//Cannot read property 'rootFolderUrl' of undefined
	session.getRepositoryInfo().ok(function (data){
		console.log("ok "+JSON.stringify(data,null,2));
	});

I am trying to talk to Alfresco v4.2. "loadRepositories()" works fine. However i tried "getRepositoryInfo", "getChildren" , "query", all give the same error as "Cannot read property 'rootFolderUrl' of undefined".

**Comment by jaawerth** [comment]
That error typically comes up if you try using any of those sorts of functions before the call to loadRepositories has finished (which is what would happen in the code above). Did you make sure that second call is in a function being invoked by the callback for loadRepositories, or in a chained promise or something along those lines to handle the async stuff?

**Comment by agea** [comment]
`loadRepositories()` is asynchronous (like almost all CmisSession methods), so you have to be sure to make subsequent calls after it has completed the request:

```javascript
var url = "http://xxx:8080/alfresco/cmisbrowser";
var session = cmis.createSession(url);
session.setCredentials('admin','7Tablets!');

session.loadRepositories().ok(function (data){
    session.getRepositoryInfo().ok(function (data){
        console.log("ok "+JSON.stringify(data,null,2));
    });
});



```
