### ISSUE TITLE
getChildren doesn't return any data

### ISSUE THREAD

**Issue by YogeshGK** [agea/CmisJS#24]
Running code against alfred 4.2. I have a site named mySite (type: F:st:site) in Sites . The full path is of site is "/Sites/mySite". Some pics are uploaded in documentLibrary(type: cmis:folder) for that site at "/Sites/mySite/documentLibrary".  
'getChildren()' returns correct data when passed object_id of "/" or "/Sites" or "/Sites/mySite/".
But it doesn't return any data when passed id of "/Sites/mySite/documentLibrary". I have check "notOk" and "error" cases too it doesn't go there. It returns in "ok" with no data.

**Comment by agea** [comment]
Are you using an admin user to make test (do you have the permissions to see the children of /Sites/mySite/documentLibrary )?

You can use https://github.com/agea/cmis-web-workbench to make some tests

**Comment by YogeshGK** [comment]
I was using OpenCMIS workbench with same account and i could see the documents inside documentLibrary.I used "http://xxx:8080/alfresco/api/-default-/cmis/versions/1.0/atom" to connect to alfresco. And yes its a admin account.

**Comment by jaawerth** [comment]
You want the browser binding. Try  `/alfresco/api/-default-/public/cmis/versions/1.1/browser`, that's what I'm using with 4.2.

**Comment by 4F2E4A2E** [comment]
@YogeshGK any status on this? getChildren() is working just fine for us.

**Comment by agea** [comment]
Closing, as there are no updates
