### ISSUE TITLE
Question about "createDocumentFromSource" method

### ISSUE THREAD

**Issue by wiser** [agea/CmisJS#26]
Hi,

I use your (great...) library in a nodeJS module.
My goal is to create a new document from an already existing one (and I have to keep the source content).
So I use the "createDocumentFromSource" and it seems I have to give a parameter (the 3rd) with some content...
First, I try with null, empty and undefined keyword, but I got an error.
So I try with an empty string, so I don't get an error, but the created document has an empty source (ok, logical...).
So my question is, how can I manage to keep the original content of the source document ?
Of course, I can get the content of the source document and put it in 3rd parameter but it's not very pretty because of the "goings and comings" on network...
Weird thing : If I use the library outside of nodeJs, it seems that I can omit the 3rd parameter then it works as wished...

Thx in advance for your job and your help.
BR
Wiser.

**Comment by agea** [comment]
Thank you for closing your issues (and for fixing my bugs)
