### ISSUE TITLE
setToken does not work with Alfresco ticket

### ISSUE THREAD

**Issue by evoci** [agea/CmisJS#30]
Alfresco authentication returns a ticket string to use for all RESTFUL calls after login.
CmisJS apparently is incompatible with that ticket.
I am able to place calls after setCredentials, however would prefer using tokens instead.
This is to ask how to manage (obtain/use) the token to avoid an authentication with password in clear text.

**Comment by agea** [comment]
I don't think Alfresco CMIS implementation allows token authentication (at least neither I've been able to use it). Once you have received a valid alfresco ticket you can set 'ROLE_TICKET' as username and the ticket as password in the setCredentials() call

**Comment by e-voci** [comment]
Thanks, that worked.
Anyhow, can you please explain from where can the token be obtained in "normal" operations?

**Comment by agea** [comment]
I just implemented the CMIS specifications, in my experience I never found a way to use the token..
