### ISSUE TITLE
getFolderTree() wrong CMIS Selector?

### ISSUE THREAD

**Issue by 4F2E4A2E** [agea/CmisJS#35]
Hey there!
First of all, thank you for this amazing lib.
We saw that this method is beeing covered in the tests, but getFolderTree() is only working for us if we change the CMIS Selector from 'folderTree' to 'folder', https://github.com/agea/CmisJS/blob/dcf57e59b7203e80373469229f160f31152baeb9/lib/cmis.js#L659

Can you tell why?`
We are using Alfresco 4.2 and CMIS 1.1 via Browser-Binding

Cheers

**Comment by agea** [comment]
The library follows the specification: http://docs.oasis-open.org/cmis/CMIS/v1.1/errata01/os/CMIS-v1.1-errata01-os-complete.html#x1-5800003 (see 5.4.3.3)

If I recall correctly Alfresco 4.2 support of Browser Bindings 1.1 was marked as **experimental**. On 5.x versions the method works as expected.
