### ISSUE TITLE
createDocument inputs

### ISSUE THREAD

**Issue by wiser** [agea/CmisJS#36]
Hi,

I'm still a user of your great library ;)

I have a question about the inputs used for the "createDocument" operation.
According to the documentation, there is 2 required parameters : repositoryId & properties (array).
There is also some optionals like "folderId", "contentStream" and so on...
When I read your "createDocument" method, I can see you set "options.objectId" with the "parentId" parameter.
Is this a mistake ? I think we should have "options.folderId" instead of "options.objectId".

If you are agree with that, I can suggest you a PR.

BR.
Wiser.

**Comment by agea** [comment]
I don't remember why the library uses `objectId` instead of `folderId`, probably beacuse the Alfresco implementation when I developed the library only worked with `objectId` as parameter..

Any PR is welcome, tank you!

**Comment by wiser** [comment]
Hi,

As I suggested to you, I prepared a PR.
But with my modifications, the 'createDocument' test do not pass anymore because of an error :
```
{
    "exception" : "contentAlreadyExists",
    "message"  : "An object with this name already exists: Existing file or folder test.txt already exists"
}
```
Obviously, the Alfresco repository does not recognize the folderId parameter of the createDocument method because it tries to create the "test.txt" file on the root folder instead of the previously created random folder...

Of course, I don't want to break your compatibility with Alfresco, so I guess you can close this issue, I will adapt my CMIS server implementation to accept the objectId parameter if folderId is not sent...

Wiser.

**Comment by agea** [comment]
Ok, thank you
