### ISSUE TITLE
Andrea, are you planning to continue the contribution to this project?

### ISSUE THREAD

**Issue by eduardoeriquelme** [agea/CmisJS#50]
The reason I ask is because I would like to present this project as a solution for  CMIS UI. However, if we decide to go with CmisJS, it would be used for many years.

**Comment by agea** [comment]
Hi, I do not plan to stop contributing to this project, but keep in mind that I cannot guarantee any kind of support for this project

**Comment by eduardoeriquelme** [comment]
Fair enough. Thanks!
